#!/usr/bin/env python3
"""
Devotional Audio Agent — Narrates approved daily devotions via ElevenLabs
Reads from: workflows/output/substack-approved/[YYYY-MM-DD].md
            (falls back to workflows/output/substack-pending/ if no approved
            drafts exist yet, so the pipeline can be tested before Grace signs off)
Narrates via: ElevenLabs text-to-speech REST API
Writes to: workflows/output/devotional-audio/[YYYY-MM-DD].mp3
Logs to: workflows/devotional-audio-log.md

This is a separate, optional step from the Substack text pipeline
(workflows/scripts/substack_agent.py / substack-deploy.py). Audio narration
was never part of the original daily-devotion spec in
content-ops/05_substack/agent.md — it produces text only. This script exists
so a devotion CAN also get a spoken narration, on request, the same way the
six gate pages and daily-sanctuary.html already do (see PROJECT_STATUS.md,
"Gate voiceover audio"). Those were generated by hand in an ElevenLabs
session; this script makes the step repeatable and automatable.

Requires ELEVENLABS_API_KEY in the environment (GitHub Secret, when run in
Actions). As of this writing that secret does NOT exist in this repo's
workflow YAML — see .github/workflows/*.yml — so this script is not wired
into any cron job. Run it manually, or add the secret and a workflow step
once Grace decides she wants daily narration automated.
"""

import os, re, sys, pathlib, datetime, json, urllib.request, urllib.error

ELEVENLABS_API_KEY = os.environ.get('ELEVENLABS_API_KEY', '').strip()

# Matilda — the voice already used for the six gate recordings and
# daily-sanctuary.html, kept as the default here for consistency across the
# ministry's audio. Override with ELEVENLABS_VOICE_ID if Grace wants a
# different voice for devotional narration specifically.
DEFAULT_VOICE_ID = 'XrExE9yKIg1WjnnlVkGX'  # Matilda
VOICE_ID = os.environ.get('ELEVENLABS_VOICE_ID', DEFAULT_VOICE_ID).strip()
MODEL_ID = os.environ.get('ELEVENLABS_MODEL_ID', 'eleven_multilingual_v2').strip()

APPROVED_DIR = pathlib.Path('workflows/output/substack-approved')
PENDING_DIR = pathlib.Path('workflows/output/substack-pending')
OUTPUT_DIR = pathlib.Path('workflows/output/devotional-audio')
LOG_FILE = pathlib.Path('workflows/devotional-audio-log.md')

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def strip_frontmatter(text):
    """Remove the leading --- ... --- YAML block a devotion draft is saved with."""
    lines = text.split('\n')
    if lines and lines[0].strip() == '---':
        for i in range(1, len(lines)):
            if lines[i].strip() == '---':
                return '\n'.join(lines[i + 1:]).strip()
    return text.strip()


def clean_for_speech(body):
    """Drop markdown headers/links/CTAs that read fine but narrate badly."""
    body = re.sub(r'^#+\s*', '', body, flags=re.MULTILINE)
    body = re.sub(r'\*+', '', body)
    body = re.sub(r'https?://\S+', '', body)
    body = re.sub(r'\n{3,}', '\n\n', body)
    return body.strip()


def pick_source_file():
    """Prefer an approved devotion; fall back to the newest pending draft."""
    if APPROVED_DIR.exists():
        approved = sorted(APPROVED_DIR.glob('*.md'))
        if approved:
            return approved[-1], 'approved'
    if PENDING_DIR.exists():
        pending = sorted(PENDING_DIR.glob('*.md'))
        if pending:
            return pending[-1], 'pending'
    return None, None


def log_entry(date_str, status, detail=''):
    LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
    if not LOG_FILE.exists():
        LOG_FILE.write_text(
            "# Devotional Audio Log\n"
            "## Sanctuary Grace Ministry · The Quiet Authority\n\n"
            "| Date | Status | Detail |\n|---|---|---|\n"
        )
    with LOG_FILE.open('a') as f:
        f.write(f"| {date_str} | {status} | {detail} |\n")


def main():
    devo_file, source = pick_source_file()
    if not devo_file:
        print("No approved or pending devotion found. Nothing to narrate.")
        sys.exit(0)

    date_str = devo_file.stem
    out_path = OUTPUT_DIR / f"{date_str}.mp3"

    if out_path.exists():
        print(f"{date_str}: audio already exists at {out_path}. Skipping.")
        log_entry(date_str, "SKIPPED (exists)", str(out_path))
        sys.exit(0)

    raw = devo_file.read_text()
    body = clean_for_speech(strip_frontmatter(raw))

    if not body:
        print(f"⚠️  {date_str}: no narratable text found. Skipping.")
        log_entry(date_str, "SKIPPED (empty)", str(devo_file))
        sys.exit(0)

    if not ELEVENLABS_API_KEY:
        print("⚠️  ELEVENLABS_API_KEY not set. Skipping narration.")
        print(f"   Would have narrated ({source}): {devo_file}")
        log_entry(date_str, "SKIPPED (no API key)", str(devo_file))
        sys.exit(0)

    print(f"Narrating {source} devotion {date_str} ({len(body)} chars) with voice {VOICE_ID}...")

    payload = json.dumps({
        "text": body,
        "model_id": MODEL_ID,
        "voice_settings": {"stability": 0.5, "similarity_boost": 0.75},
    }).encode('utf-8')

    req = urllib.request.Request(
        f'https://api.elevenlabs.io/v1/text-to-speech/{VOICE_ID}',
        data=payload,
        headers={
            'Content-Type': 'application/json',
            'Accept': 'audio/mpeg',
            'xi-api-key': ELEVENLABS_API_KEY,
        },
        method='POST',
    )

    try:
        with urllib.request.urlopen(req, timeout=120) as response:
            audio_bytes = response.read()
            out_path.write_bytes(audio_bytes)
            print(f"✅ {date_str}: narration saved to {out_path} ({len(audio_bytes)} bytes)")
            log_entry(date_str, "AUDIO SAVED", str(out_path))
    except urllib.error.HTTPError as e:
        error_body = e.read().decode(errors='replace')
        print(f"❌ {date_str}: ElevenLabs HTTP {e.code} — {error_body[:200]}")
        log_entry(date_str, f"FAILED (HTTP {e.code})", error_body[:200])
        sys.exit(1)
    except Exception as e:
        print(f"❌ {date_str}: {e}")
        log_entry(date_str, "FAILED", str(e))
        sys.exit(1)


if __name__ == '__main__':
    main()
